apiVersion: v1
kind: Service
metadata:
  name: plasmatech-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
    service.beta.kubernetes.io/linode-loadbalancer-default-protocol: http
    service.beta.kubernetes.io/linode-loadbalancer-port-443: '{ "tls-secret-name": "ssl-cert-secret", "protocol": "https" }'
  labels:
    app: plasmatech-service
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: plasmatech-webserver
  sessionAffinity: None